export type HelpArticle = {
  slug: string;
  section: string;
  title: string;
  summary: string;
  audience: string;
  overview: string;
  steps: string[];
  links: { label: string; href: string }[];
  caution?: string;
};

export const helpArticles: HelpArticle[] = [
  {
    slug: 'how-buildnerve-works', section: 'Start here', title: 'How BuildNerve works', audience: 'Everyone',
    summary: 'Understand the job record and how the main parts of the product connect.',
    overview: 'BuildNerve brings a contractor’s jobs, people, clients, site records and commercial work into one workspace. Start with a client and job, then attach the activity and decisions to that job. Access depends on your organisation and role.',
    steps: ['Create an account or accept an invitation to an organisation.', 'Set up a client and create a job.', 'Add the people working on it and record daily activity.', 'Keep variations, evidence, payments and deadlines with the job.', 'Use reports and notifications to review what needs attention.'],
    links: [{ label: 'Create an account', href: '/sign-up' }, { label: 'Jobs', href: '/jobs' }],
    caution: 'The repository contains both connected and demonstration screens. Check each guide for its current data status before using a screen for a live business decision.',
  },
  {
    slug: 'public-website', section: 'Start here', title: 'Using the public website', audience: 'Visitors',
    summary: 'Find product information, pricing, legal documents and account access.',
    overview: 'The public pages introduce BuildNerve and provide pricing and legal information. The signed-in workspace is separate from the marketing site.',
    steps: ['Use the home page to explore the product areas and workflow.', 'Open Pricing to compare the listed plans and frequently asked questions.', 'Choose Sign in if you already have an account, or Sign up to start.', 'Open the Legal & Trust Centre for policies and company information.'],
    links: [{ label: 'Home', href: '/' }, { label: 'Pricing', href: '/pricing' }, { label: 'Legal & Trust Centre', href: '/legal' }],
    caution: 'Some public footer links still point to “#”, and plan claims should be checked against the actual enabled capabilities before purchase.',
  },
  {
    slug: 'account-and-invitations', section: 'Start here', title: 'Accounts, sign-in and invitations', audience: 'Organisation users',
    summary: 'Sign in, reset a password and join an organisation.',
    overview: 'Your account identifies you; organisation membership determines which workspace data you can access.',
    steps: ['Create an account on Sign up or use the link in an organisation invitation.', 'Confirm your email if prompted.', 'Sign in with your account credentials.', 'Use Forgot password on the sign-in page if you cannot access your account.', 'If an invitation fails, ask the organisation administrator to check or resend it.'],
    links: [{ label: 'Sign in', href: '/sign-in' }, { label: 'Reset access', href: '/forgot-password' }],
  },
  {
    slug: 'dashboard', section: 'Workspace', title: 'Understand the dashboard', audience: 'Organisation users',
    summary: 'Find the navigation, Assist panel, alerts and business overview.',
    overview: 'The sidebar takes you to the main workspaces. The top bar offers account controls and Assist. The command centre shows KPIs, deadlines, approvals, field activity and quick links.',
    steps: ['Sign in and open Overview.', 'Use the sidebar on desktop or the mobile navigation to move between areas.', 'Open a linked item to inspect its underlying record.', 'Use the Assist button for questions, then check cited source records.'],
    links: [{ label: 'Overview', href: '/app' }, { label: 'AI settings', href: '/app/settings/ai-automation' }],
    caution: 'The current executive dashboard includes fixed Apex Construction sample content and a fixed August 2026 date. Treat its headline figures as a design demonstration until connected to your organisation’s data.',
  },
  {
    slug: 'clients', section: 'Jobs and people', title: 'Manage clients', audience: 'Office team',
    summary: 'Find client records and associate a client with a job.',
    overview: 'Clients hold contact and address information used by jobs and the client-facing workflow.',
    steps: ['Open Clients to find a client record.', 'When creating a job, select an existing client or enter a new client.', 'Check billing and site addresses before creating the job.', 'Open the client record to review available linked information.'],
    links: [{ label: 'Clients', href: '/clients' }, { label: 'Create a job', href: '/jobs/new' }],
  },
  {
    slug: 'create-job', section: 'Jobs and people', title: 'Create a job', audience: 'Office team',
    summary: 'Use the job wizard to set up a project and contract details.',
    overview: 'A job is the central record for project activity. The creation wizard saves an unfinished draft in this browser.',
    steps: ['Open Jobs and select New job.', 'Choose an existing client or enter a new one.', 'Add the job name, reference, location, commercial and team details.', 'Upload a contract if relevant and review any extracted terms.', 'Review the final summary and create the job.'],
    links: [{ label: 'New job', href: '/jobs/new' }, { label: 'Jobs', href: '/jobs' }],
    caution: 'You need an organisation selected to create a job. A duplicate reference is rejected. Browser draft storage is device-local; verify dates and amounts against the contract.',
  },
  {
    slug: 'job-workspace', section: 'Jobs and people', title: 'Use a job workspace', audience: 'Project team',
    summary: 'Find a job’s timeline, logs, documents, evidence and payments.',
    overview: 'Open a job from Jobs to work from its project record. Related routes include timeline, daily logs, evidence pack, reports and job payments.',
    steps: ['Open Jobs and select the correct job.', 'Choose the relevant tab or linked workspace.', 'Check that any new record refers to the right job.', 'Return to the job to review activity and outstanding items.'],
    links: [{ label: 'Jobs', href: '/jobs' }],
    caution: 'The current job detail page imports demonstration job and related records. Do not assume every item shown there is persisted organisation data.',
  },
  {
    slug: 'workforce', section: 'Jobs and people', title: 'Workforce and subcontractor invitations', audience: 'Office team',
    summary: 'Invite people and review their work profiles and documents.',
    overview: 'The Workforce area groups people, invitations and document or compliance information.',
    steps: ['Open Workforce and search for the person.', 'Use Invite to add a subcontractor.', 'Check the invitation details and intended access before sending.', 'Open the person’s profile to review their documents and status.'],
    links: [{ label: 'Workforce', href: '/workforce' }, { label: 'Invite a subcontractor', href: '/workforce/invite' }],
    caution: 'Verify insurance, qualifications and expiry dates independently before assigning regulated or safety-critical work.',
  },
  {
    slug: 'daily-logs', section: 'Site and mobile', title: 'Write daily site logs', audience: 'Site team',
    summary: 'Record the day’s work against the correct job.',
    overview: 'Daily logs provide a dated project record of work and site conditions.',
    steps: ['Open a job and choose Daily logs.', 'Create a new log for the day.', 'Record the work, people and relevant events accurately.', 'Review and save the log, then confirm it appears in the list.'],
    links: [{ label: 'Find a job', href: '/jobs' }],
  },
  {
    slug: 'evidence', section: 'Site and mobile', title: 'Evidence, photos and site capture', audience: 'Site and office teams',
    summary: 'Find evidence and understand the current capture limitations.',
    overview: 'Evidence records are intended to connect photos, notes and site events with jobs. Check visibility before sharing with a client.',
    steps: ['Open Evidence and find the relevant item.', 'Open its detail to inspect the job, type and review status.', 'For a new capture, select the right job and record type.', 'Confirm that the saved record appears in the evidence list before relying on it.'],
    links: [{ label: 'Evidence', href: '/evidence' }],
    caution: 'The separate /site/:jobId/capture page currently uses demo jobs, a simulated file selection and a save toast without persistence. A success message there is not proof of an upload.',
  },
  {
    slug: 'mobile-offline', section: 'Site and mobile', title: 'Mobile workspace and offline work', audience: 'Site team',
    summary: 'Navigate Today, Jobs, Tasks and Sync on a phone.',
    overview: 'Mobile mode provides a smaller navigation and screens for site work, device management and sync.',
    steps: ['Open Mobile Today and choose a job or task.', 'Check the connection indicator before working.', 'Open Sync to inspect queued items and conflicts.', 'After reconnecting, confirm each important record appears in the main workspace.'],
    links: [{ label: 'Mobile Today', href: '/mobile/today' }, { label: 'Sync', href: '/mobile/sync' }],
    caution: 'Mobile Today and parts of Sync use sample job data in the current code. Test offline persistence and conflict handling on your device before using it as a live site record.',
  },
  {
    slug: 'variations', section: 'Commercial', title: 'Variations and approvals', audience: 'Commercial and project teams',
    summary: 'Record a change to scope, cost or programme.',
    overview: 'A variation ties a proposed change to a job and its approval history.',
    steps: ['Open Variations and choose New variation.', 'Select the correct job and describe the change.', 'Enter the impact and attach supporting information where offered.', 'Review before submission and follow its status in Variations.'],
    links: [{ label: 'Variations', href: '/variations' }, { label: 'New variation', href: '/variations/new' }],
    caution: 'Retain the underlying client instruction and evidence. Check contract-specific approval rules outside the app.',
  },
  {
    slug: 'payments', section: 'Commercial', title: 'Payment applications and the Payments area', audience: 'Commercial team',
    summary: 'Distinguish job payment records from the overview screen.',
    overview: 'Job payment applications are accessed from a specific job. The top-level Payments workspace presents a broader payment and notice overview.',
    steps: ['Open Jobs and select the relevant job.', 'Open its Payments route to review applications and amounts.', 'Check dates, certification and status against the contract.', 'Use the top-level Payments area for orientation only until its source data is verified.'],
    links: [{ label: 'Jobs', href: '/jobs' }, { label: 'Payments overview', href: '/payments' }],
    caution: 'The top-level Payments page imports mock retention and valuation data. The job payment page calls Supabase services. Neither replaces contract or accounting verification.',
  },
  {
    slug: 'retention', section: 'Commercial', title: 'Retention and release milestones', audience: 'Commercial team',
    summary: 'Review retention amounts and upcoming release points.',
    overview: 'The Retention workspace groups summary cards, a release pipeline, alerts and a ledger view.',
    steps: ['Open Retention and identify the job or milestone.', 'Check the amount and release condition against the contract.', 'Confirm any notice or payment action in the underlying job and accounting records.'],
    links: [{ label: 'Retention', href: '/retention' }],
    caution: 'Validate the workspace figures and milestone status against source records before issuing a payment or notice.',
  },
  {
    slug: 'deadlines', section: 'Commercial', title: 'Deadlines and notices', audience: 'Commercial team',
    summary: 'Use calendar and list views for dates requiring review.',
    overview: 'Deadline rules can be generated from contract information and related events. The page offers calendar and list views.',
    steps: ['Open Deadlines and filter the list or calendar.', 'Inspect the job, contract type and source event.', 'Check the actual contract wording and service requirements.', 'Record the action taken before the deadline.'],
    links: [{ label: 'Deadlines', href: '/deadlines' }],
    caution: 'The page can fall back to demo deadlines. Generated dates and notice text are prompts for review, not legal advice.',
  },
  {
    slug: 'disputes', section: 'Commercial', title: 'Disputes and legal guidance', audience: 'Commercial team',
    summary: 'Organise case records and supporting evidence.',
    overview: 'The dispute workspace provides case creation, detail and a separate legal guidance area.',
    steps: ['Open Dispute Resolution and review existing cases.', 'Raise a case with the correct job and facts.', 'Collect the relevant evidence, dates and communications.', 'Read the guidance and seek qualified advice for formal notices or proceedings.'],
    links: [{ label: 'Dispute Resolution', href: '/disputes' }, { label: 'Legal guidance', href: '/disputes/legal-guidance' }],
    caution: 'Guidance depends on jurisdiction and the specific contract. Do not treat the interface as a substitute for a solicitor or adjudication specialist.',
  },
  {
    slug: 'procurement', section: 'Operations', title: 'Procurement and suppliers', audience: 'Purchasing and project teams',
    summary: 'Follow materials from request to order, delivery and invoice.',
    overview: 'Procurement includes suppliers, materials, requisitions, RFQs, purchase orders, deliveries, inventory, hire, returns and invoice matching.',
    steps: ['Start with a supplier and material record.', 'Create a requisition or RFQ for the need.', 'Review and approve the purchase order.', 'Record the goods receipt or delivery issue.', 'Compare the supplier invoice with the order and receipt.'],
    links: [{ label: 'Procurement dashboard', href: '/app/procurement' }, { label: 'Procurement portal', href: '/procurement' }],
    caution: 'Confirm which procurement screens are connected to your organisation before treating dashboard totals as committed expenditure.',
  },
  {
    slug: 'compliance', section: 'Operations', title: 'Compliance and health and safety', audience: 'Project and safety teams',
    summary: 'Find compliance work and job safety records.',
    overview: 'The product includes a Compliance route and job-level safety concepts such as RAMS, toolbox talks and CDM duty holders.',
    steps: ['Open the relevant job to inspect its safety records.', 'Review the responsible person and document version.', 'Use Compliance to see available workspace information.', 'Get a competent human to review and approve safety documents before site use.'],
    links: [{ label: 'Compliance', href: '/compliance' }, { label: 'Jobs', href: '/jobs' }],
    caution: 'The project plan describes the Compliance route as a placeholder. Generated RAMS require competent review and site-specific checks.',
  },
  {
    slug: 'messages-notifications', section: 'Operations', title: 'Messages and notifications', audience: 'Organisation users',
    summary: 'Find conversations, alerts and notification preferences.',
    overview: 'Messages holds communication threads, while Notifications shows alerts. Organisation settings control personal notification preferences.',
    steps: ['Open Messages to find a conversation.', 'Open Notifications to review alerts that need action.', 'Use notification settings to adjust delivery preferences.', 'Check the underlying job before acting on a message or reminder.'],
    links: [{ label: 'Messages', href: '/messages' }, { label: 'Notifications', href: '/notifications' }, { label: 'Preferences', href: '/settings/notifications' }],
  },
  {
    slug: 'reports', section: 'Operations', title: 'Reports and analytics', audience: 'Managers',
    summary: 'Find job, commercial, cash flow, people and site reports.',
    overview: 'Reports includes an overview, category reports, a builder, and saved or scheduled report pages.',
    steps: ['Open Reports and choose the relevant subject.', 'Set the available filters and period.', 'Check the source records behind unusual figures.', 'Save or schedule only after confirming the report scope.'],
    links: [{ label: 'Reports', href: '/reports' }],
    caution: 'Check each report’s source and filters before sharing figures externally.',
  },
  {
    slug: 'billing-subscription', section: 'Account and settings', title: 'Plans, subscription and invoices', audience: 'Account owners',
    summary: 'Understand product billing and where to find invoices.',
    overview: 'The public Pricing page lists plans. Signed-in Billing offers plan, usage, invoice and account billing screens.',
    steps: ['Review the plan details on Pricing.', 'Sign in and open Billing to see your current subscription.', 'Use Plan or Usage for the relevant details.', 'Open Invoices for available billing history.', 'Review checkout or portal details before confirming a change.'],
    links: [{ label: 'Pricing', href: '/pricing' }, { label: 'Billing', href: '/app/settings/billing' }, { label: 'Invoices', href: '/app/settings/billing/invoices' }],
    caution: 'The public pricing copy includes specific promises about integrations, support and statutory workflows. Confirm these are enabled and included for your account before purchasing.',
  },
  {
    slug: 'integrations', section: 'Account and settings', title: 'Integrations, imports and sync', audience: 'Account owners',
    summary: 'Connect accounting providers and review sync activity.',
    overview: 'The integration hub offers provider connections, mappings, sync history, reconciliation and CSV import/export.',
    steps: ['Open Integrations and choose a provider.', 'Complete the connection steps with an authorised account.', 'Review entity and tax mappings before syncing.', 'Check Sync history and Reconciliation for failures or mismatches.', 'Use Import/export for supported CSV workflows.'],
    links: [{ label: 'Integrations', href: '/app/settings/integrations' }, { label: 'Sync history', href: '/app/settings/integrations/sync-history' }],
    caution: 'An available provider card does not prove a live connection. Check credentials, sync status and accounting totals before relying on transferred data.',
  },
  {
    slug: 'assist-ai', section: 'Account and settings', title: 'Assist and document intelligence', audience: 'Organisation users',
    summary: 'Ask questions, inspect citations and control AI use.',
    overview: 'Assist opens from the top bar. AI settings include organisation controls and usage information. Document ingestion has its own route.',
    steps: ['Open Assist and ask a specific question.', 'Include the correct job or document context where possible.', 'Inspect cited records and check important claims.', 'Use AI & Automation settings to review access, budgets and data controls.'],
    links: [{ label: 'AI settings', href: '/app/settings/ai-automation' }, { label: 'Document ingestion', href: '/app/documents/ingestion' }],
    caution: 'AI output can be incomplete or wrong. Never approve a contract term, safety instruction, invoice or legal notice without human review.',
  },
  {
    slug: 'client-portal', section: 'Clients and external users', title: 'Client project portal', audience: 'Clients and project team',
    summary: 'Understand project links, progress and approvals.',
    overview: 'Clients can use a token-based project link to see the information made available to them, including schedule and variation views.',
    steps: ['Open the project link supplied by the contractor.', 'Review the project details and available schedule.', 'Open a variation to inspect its description and terms.', 'Confirm the action and record you are approving before submission.'],
    links: [{ label: 'Clients workspace', href: '/clients' }],
    caution: 'Treat a portal link as sensitive. The exact client route requires an access token supplied for that project; do not share it publicly.',
  },
  {
    slug: 'privacy-security', section: 'Account and settings', title: 'Privacy, security and legal information', audience: 'Everyone',
    summary: 'Find policies, data handling and security information.',
    overview: 'The Legal & Trust Centre groups terms, privacy, cookies, security, AI, retention, accessibility and related documents.',
    steps: ['Open the Legal & Trust Centre.', 'Choose the document relevant to your question.', 'Use the account and device settings for available access controls.', 'Contact the organisation administrator for a specific data or access request.'],
    links: [{ label: 'Legal & Trust Centre', href: '/legal' }, { label: 'Device settings', href: '/settings/devices' }],
  },
  {
    slug: 'platform-admin', section: 'Administration', title: 'Platform administration and support', audience: 'Platform staff',
    summary: 'Understand the separate staff control plane.',
    overview: 'Platform administration has its own sign-in and MFA flow and includes organisations, users, support cases, audit, security, billing, integrations and AI monitoring.',
    steps: ['Use the platform admin sign-in and complete MFA.', 'Open the area relevant to your assigned role.', 'Review audit and access context before changing a customer record.', 'Record the outcome in the support workflow.'],
    links: [{ label: 'Platform admin sign-in', href: '/platform-admin/login' }],
    caution: 'The current Support Cases page reads demo cases and its New case, Resolve and Close buttons have no save handlers. Do not use it as a live ticket system yet.',
  },
];

export const helpSections = ['All', ...Array.from(new Set(helpArticles.map((article) => article.section)))];
